# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghd" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b90604a0c5948f5206aa8d58da6fa7d3df6ccd9a38e71a1309a84d0248069221"
      url "https://github.com/meigma/ghd/releases/download/v#{version}/ghd_#{version}_darwin_amd64"
      binary "ghd_0.1.0_darwin_amd64", target: "ghd"
    end
    on_arm do
      sha256 "7a9d7b9cece6c7156a96cdb09269a802cb2bfc6688994070f301de2f0501dcd1"
      url "https://github.com/meigma/ghd/releases/download/v#{version}/ghd_#{version}_darwin_arm64"
      binary "ghd_0.1.0_darwin_arm64", target: "ghd"
    end
  end

  on_linux do
    on_intel do
      sha256 "23289cfeebe0bdae251c7dd4415ebb0dafc852206c0774894da42f5b052914bb"
      url "https://github.com/meigma/ghd/releases/download/v#{version}/ghd_#{version}_linux_amd64"
      binary "ghd_0.1.0_linux_amd64", target: "ghd"
    end
    on_arm do
      sha256 "b592d70b65ed7cb45dae6dd8d9ffc1cec1839a3b07d1257c75e7f39d72e14b5a"
      url "https://github.com/meigma/ghd/releases/download/v#{version}/ghd_#{version}_linux_arm64"
      binary "ghd_0.1.0_linux_arm64", target: "ghd"
    end
  end

  name "ghd"
  desc "Verified GitHub release asset downloader"
  homepage "https://github.com/meigma/ghd"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
