# This file was generated by GoReleaser. DO NOT EDIT.
cask "meigma-release-cli" do
  version "0.1.7"

  on_macos do
    on_arm do
      sha256 "329ded3c9427f7518843ffdcd92b8d0daa5fea15781422fe20731506f85f5ffd"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8e9567e6d97ec19f955920b7cd63180437eafae9ea2b1b404a76e67aa50dd81a"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "573e32eb8f69a8eaaa1dfa07ac22a639da396063e70bfcc7507d8a8f697625ea"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7600055782fc9dd74389cb0b23d97f1ea3f27f4bdfa6781d5c7d18e7ed0df9bd"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "meigma-release-cli"
  desc "Release automation for Meigma projects"
  homepage "https://github.com/meigma/release"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "release-cli"

  # No zap stanza required
end
