# This file was generated by GoReleaser. DO NOT EDIT.
cask "meigma-release-cli" do
  version "0.1.18"

  on_macos do
    on_arm do
      sha256 "625d6d62b1a78ca5ff170f0094432ac3203d336647280a1559d5dae823a148e0"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ca69da13a6d32f5feb8aa16cc15baaba96b509c5ff365428b2ed2e2f3249558"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e9d2a9d9665dc8a1a6eaa7e976a263cb297d4f2e08cb6eadfe68c7b1c0615977"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5c1e4ffb5eaf5dcb06a91cbaae07c32cc7368f29108f97ddac31859d1d6d20e"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "meigma-release-cli"
  desc "Release automation for Meigma projects"
  homepage "https://github.com/meigma/release"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "release-cli"

  # No zap stanza required
end
