# This file was generated by GoReleaser. DO NOT EDIT.
cask "meigma-release-cli" do
  version "0.1.9"

  on_macos do
    on_arm do
      sha256 "6378f3f89f6ef8328da66bea83b9a83cf25d5f4471d2d190603d401875548bb5"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7726abc187d74f6f8c739cce208ffc2c1ba78dc22befb6b6d99b9ec4d142c2b7"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "cadc1fd838a9f90efc957c470bac45fa2c2870509536e62d776741cef1abf2e4"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c99cb4d1589744fbe590c2ebf92136bf33303197d838fcd1d772d12930758d19"
      url "https://github.com/meigma/release/releases/download/v#{version}/release-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "meigma-release-cli"
  desc "Release automation for Meigma projects"
  homepage "https://github.com/meigma/release"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "release-cli"

  # No zap stanza required
end
