# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blobber < Formula
  desc "Push and pull files to OCI registries"
  homepage "https://github.com/meigma/blobber"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meigma/blobber/releases/download/v1.1.0/blobber_1.1.0_darwin_amd64.tar.gz"
      sha256 "d6da39211819d304aeadb964c1c4a2f3e3818608fb2beb639d1088ac2e642f8c"

      def install
        bin.install "blobber"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meigma/blobber/releases/download/v1.1.0/blobber_1.1.0_darwin_arm64.tar.gz"
      sha256 "1df7f24f88e74c681e7b6256999d1a6aeee5a8893b17050e35050e8c4dd44797"

      def install
        bin.install "blobber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/blobber/releases/download/v1.1.0/blobber_1.1.0_linux_amd64.tar.gz"
      sha256 "05dcf5a3adecaa74c9413db73d4bd5d7880a4f79d2249da568404ac34a9eecf7"
      def install
        bin.install "blobber"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/blobber/releases/download/v1.1.0/blobber_1.1.0_linux_arm64.tar.gz"
      sha256 "e392ea0d02a929c203831e1c71cc07975ef1284e935a0a8e9400dd921a7b58f6"
      def install
        bin.install "blobber"
      end
    end
  end

  test do
    system "#{bin}/blobber", "version"
  end
end
