# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blobber < Formula
  desc "Push and pull files to OCI registries"
  homepage "https://github.com/meigma/blobber"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meigma/blobber/releases/download/v1.0.0/blobber_1.0.0_darwin_amd64.tar.gz"
      sha256 "028b1ec4382a9c16f361bbf2db31ab8e4f8f8f58d429825405bb755d87c11a8d"

      def install
        bin.install "blobber"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meigma/blobber/releases/download/v1.0.0/blobber_1.0.0_darwin_arm64.tar.gz"
      sha256 "a11796d6708c34a1acedbb74120c632ed2921d94f1eb7ac9365827173ed4029c"

      def install
        bin.install "blobber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/blobber/releases/download/v1.0.0/blobber_1.0.0_linux_amd64.tar.gz"
      sha256 "0e9647f03dab44e8cb53eed9dd0bd8282491e2afd017da6dcf7e0470896cd52c"
      def install
        bin.install "blobber"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/blobber/releases/download/v1.0.0/blobber_1.0.0_linux_arm64.tar.gz"
      sha256 "3e960bf1e7edf6620aeb1b0c52ba47fa2c264bd197e45cc202cf5d60f38e6c09"
      def install
        bin.install "blobber"
      end
    end
  end

  test do
    system "#{bin}/blobber", "version"
  end
end
