# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blob < Formula
  desc "A CLI for working with blob archives in OCI registries"
  homepage "https://github.com/meigma/blob-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meigma/blob-cli/releases/download/v1.0.0/blob_1.0.0_darwin_amd64.tar.gz"
      sha256 "79c5ff3b39cfc22a748be3413546f0c0705782ba0de1fb0feb2acf72521614ac"

      def install
        bin.install "blob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meigma/blob-cli/releases/download/v1.0.0/blob_1.0.0_darwin_arm64.tar.gz"
      sha256 "df7f759d1350a55dcf6c7836d6e1b2705b0d55262aac9c50fc52cf9ac52ed9a5"

      def install
        bin.install "blob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/blob-cli/releases/download/v1.0.0/blob_1.0.0_linux_amd64.tar.gz"
      sha256 "40d9169990c5e8435f0d43d114ecd8c73be888277dbc01817b8334b3b5aebcb0"
      def install
        bin.install "blob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/blob-cli/releases/download/v1.0.0/blob_1.0.0_linux_arm64.tar.gz"
      sha256 "c18e7e18d83087af8bb43c1eef64ba91139b7d31df066d8a97a0736cf64568df"
      def install
        bin.install "blob"
      end
    end
  end

  test do
    system "#{bin}/blob", "version"
  end
end
