# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cuefn < Formula
  desc "Crossplane v2 composition function that renders Kubernetes resources from CUE modules"
  homepage "https://github.com/meigma/crossplane-cuefn"
  version "0.1.3"
  license "Apache-2.0 OR MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meigma/crossplane-cuefn/releases/download/v0.1.3/cuefn_0.1.3_darwin_amd64.tar.gz"
      sha256 "b09859b88c7487abd5e5ab9eb1d7a8bc3d404649e7affc2ae4a0b12c34b761a7"

      define_method(:install) do
        bin.install "cuefn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meigma/crossplane-cuefn/releases/download/v0.1.3/cuefn_0.1.3_darwin_arm64.tar.gz"
      sha256 "3314727e4df1c6310e9f7bcb90902b003d7162f88724e04faea260bbd59ac2c9"

      define_method(:install) do
        bin.install "cuefn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/crossplane-cuefn/releases/download/v0.1.3/cuefn_0.1.3_linux_amd64.tar.gz"
      sha256 "1841b30a68e1546eb81330b32dbc77cede361c4044cd57c937b27fe604593f8a"
      define_method(:install) do
        bin.install "cuefn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/crossplane-cuefn/releases/download/v0.1.3/cuefn_0.1.3_linux_arm64.tar.gz"
      sha256 "4cb3969c24f310b76e1d246069d2278c9d196831f56a823c8a6398a6f5bda333"
      define_method(:install) do
        bin.install "cuefn"
      end
    end
  end

  test do
    system "#{bin}/cuefn", "--version"
  end
end
