# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whzbox < Formula
  desc "A small Go CLI for managing Whizlabs cloud sandboxes"
  homepage "https://github.com/meigma/whzbox"
  version "1.0.3"
  license "MIT OR Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meigma/whzbox/releases/download/v1.0.3/whzbox_1.0.3_darwin_amd64.tar.gz"
      sha256 "e21bc503e4eaf5fccaad11a07b0992791fb6710366217344241997c728ecfc7d"

      define_method(:install) do
        bin.install "whzbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meigma/whzbox/releases/download/v1.0.3/whzbox_1.0.3_darwin_arm64.tar.gz"
      sha256 "b5aadda21bb55418161cd0e4a44a8058f786ed5ec7f8365f607b60aeeeee95f6"

      define_method(:install) do
        bin.install "whzbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/whzbox/releases/download/v1.0.3/whzbox_1.0.3_linux_amd64.tar.gz"
      sha256 "ebefe3d13b2a96cc8af6e5f4685e651e621f394c88366c1236c814065fb50ad7"
      define_method(:install) do
        bin.install "whzbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/whzbox/releases/download/v1.0.3/whzbox_1.0.3_linux_arm64.tar.gz"
      sha256 "78d34037ec0f33bea2a874df9c562e4b9754398abf44cb11a4185543c5190b1c"
      define_method(:install) do
        bin.install "whzbox"
      end
    end
  end

  test do
    system "#{bin}/whzbox", "version"
  end
end
