# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whzbox < Formula
  desc "A small Go CLI for managing Whizlabs cloud sandboxes"
  homepage "https://github.com/meigma/whzbox"
  version "1.1.0"
  license "MIT OR Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meigma/whzbox/releases/download/v1.1.0/whzbox_1.1.0_darwin_amd64.tar.gz"
      sha256 "874da515dd93fce8675a2bd5fa1e0b1aab93cd4d60a5b66e1387abc353d8b31e"

      define_method(:install) do
        bin.install "whzbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meigma/whzbox/releases/download/v1.1.0/whzbox_1.1.0_darwin_arm64.tar.gz"
      sha256 "9b658d8be14ab428ecddeade437204046f73444c4a74fadf2163060a9d5df03e"

      define_method(:install) do
        bin.install "whzbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/whzbox/releases/download/v1.1.0/whzbox_1.1.0_linux_amd64.tar.gz"
      sha256 "6dca39d548b6955e21a6fc9ee24c11d724af82491efdbdb59cbd8e643e93eb0f"
      define_method(:install) do
        bin.install "whzbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/whzbox/releases/download/v1.1.0/whzbox_1.1.0_linux_arm64.tar.gz"
      sha256 "61ad31a5e9b1dc64111031424bc818fecc37547bc6361691b9d1666aaa772fa5"
      define_method(:install) do
        bin.install "whzbox"
      end
    end
  end

  test do
    system "#{bin}/whzbox", "version"
  end
end
