# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whzbox < Formula
  desc "A small Go CLI for managing Whizlabs cloud sandboxes"
  homepage "https://github.com/meigma/whzbox"
  version "1.1.0"
  license "MIT OR Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meigma/whzbox/releases/download/v1.1.0/whzbox_1.1.0_darwin_amd64.tar.gz"
      sha256 "7cbb07e1f0dab1876c4034a13f546ec6e6aaf1b1dc2df7a957a56e7399c1d2c1"

      define_method(:install) do
        bin.install "whzbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meigma/whzbox/releases/download/v1.1.0/whzbox_1.1.0_darwin_arm64.tar.gz"
      sha256 "f14802610afde0889ae943a7c96e71fd20824db37e2174bdcc539c6246cdd7d8"

      define_method(:install) do
        bin.install "whzbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/whzbox/releases/download/v1.1.0/whzbox_1.1.0_linux_amd64.tar.gz"
      sha256 "29c6ccf3fe30b33d3af36a15650d9d48b28c0a452acc3bc021251b7842a7809d"
      define_method(:install) do
        bin.install "whzbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meigma/whzbox/releases/download/v1.1.0/whzbox_1.1.0_linux_arm64.tar.gz"
      sha256 "75b1d7dcc1f1b0e2433474b7509ec6b44c0928d33f8947fa197fda9749831d46"
      define_method(:install) do
        bin.install "whzbox"
      end
    end
  end

  test do
    system "#{bin}/whzbox", "version"
  end
end
