name: Cask CI

on:
  pull_request:
    paths:
      - 'Casks/**'

permissions: {}

jobs:
  casks:
    permissions:
      contents: read
    uses: meigma/release/.github/workflows/homebrew-tap-ci.yml@ad0e97881556a7d603a1618e46c0129c380f82fe
